// rb_image_test.cpp — PNG load + box-average downscale (DOOM-0042).
//
// Fixture is a committed bring-up PNG generated by scripts/make_bringup_hero.py — no fragile
// on-the-fly generation. _unittest_solid.png is a dedicated solid 180-grey 64x128 field (kept
// separate from the visual maps, which change per task), so a downscale must preserve ~180
// everywhere: a clean box-average check.
//
// The path is anchored to DOOM_TESTS_ROOT (the absolute path of linuxdoom-1.10/, passed by
// the Makefile) rather than being CWD-relative. It used to be a bare "../assets/..." literal,
// which resolved only when the binary was run from linuxdoom-1.10/ — true under `make test`,
// but running the binary directly from anywhere else failed inside the image loader and
// reported as a mysterious test failure rather than a wrong working directory.
#include "check_util.h"

#include <cstdio>
#include "../rb_image.c"   // single-TU: pulls in the stb impl + wrappers.
                           // (rb_image.h self-guards its decls with extern "C".)

#ifndef DOOM_TESTS_ROOT
#define DOOM_TESTS_ROOT "."     /* fallback == the old CWD-relative behaviour */
#endif
static const char* SOLID = DOOM_TESTS_ROOT "/../assets/ultra/heroes/bringup/_unittest_solid.png";

int main()
{
    rb_image_t img;

    int missing = rb_image_load("/does/not/exist.png", &img);
    check(missing == 0, "loading a missing file fails cleanly (never crashes)");

    int loaded = rb_image_load(SOLID, &img);
    check(loaded == 1, "the solid-grey fixture PNG loads");
    if (loaded != 1)
    {
        std::printf("  (fixture path was %s)\n", SOLID);
        return check_summary("rb_image");
    }

    check(img.w == 64 && img.h == 128, "fixture decodes at its authored 64x128 size");
    check(img.pixels[0] >= 176 && img.pixels[0] <= 184, "first texel is the authored ~180 grey");
    check(img.pixels[3] == 255, "an RGB source decodes to opaque alpha");

    rb_image_downscale_max(&img, 32);   // longest edge 128 -> 32 (=> 16x32)
    check(img.w == 16 && img.h == 32, "downscale to a 32px longest edge preserves aspect (16x32)");

    bool greyOk = true, alphaOk = true;
    for (int i = 0; i < img.w * img.h; i++)
    {
        if (img.pixels[i * 4 + 0] < 176 || img.pixels[i * 4 + 0] > 184) greyOk = false;
        if (img.pixels[i * 4 + 3] != 255) alphaOk = false;
    }
    check(greyOk, "box-average downscale keeps a solid field at ~180 everywhere");
    check(alphaOk, "downscale keeps every texel opaque");

    rb_image_free(&img);
    return check_summary("rb_image");
}
