// Generated formula functions — DO NOT EDIT.
// Generated by FormulaCompiler from the Vestige formula library.
// Generated by Vestige Formula Workbench v1.19.0
// library hash: 2e85f06f6ccbf3de

// Vestige SafeMath prelude — matches engine/formula/safe_math.h.
// See AUDIT.md §H12 / FIXPLAN E4 and AUDIT M11 for motivation.
float safeDiv(float l, float r) { return (r == 0.0) ? 0.0 : (l / r); }
float safeSqrt(float x) { return sqrt(abs(x)); }
float safeLog(float x) { return (x > 0.0) ? log(x) : 0.0; }
float safePow(float b, float e) {
    if (b < 0.0) {
        float r = floor(e + 0.5);
        if (abs(e - r) < 1e-6) { return pow(b, e); }
        return 0.0;
    }
    return pow(b, e);
}

// aces_tonemap — ACES filmic tone mapping curve (Narkowicz fit). Maps HDR radiance to [0,1] LDR with film-like shoulder and toe.
// source: Narkowicz 2015 ACES fit; matches scene.frag.glsl acesToneMap(). APPROXIMATE = Reinhard 2002   R²: 1
float acesTonemap(float x)
{
    return safeDiv((x * ((2.51 * x) + 0.029999999)), ((x * ((2.4300001 * x) + 0.58999997)) + 0.14));
}

// adaptive_sample_count — Variance-driven adaptive sample count (spp): n = clamp(floor(k*sqrt(variance) + 0.5), nMin, nMax). Engine template, not a published formula — fit k/nMin/nMax to captured per-pixel variance.
// source: engine template — fit k/nMin/nMax to captured variance   R²: 1
float adaptiveSampleCount(float variance)
{
    return min(16.0, max(1.0, floor(((8.0 * safeSqrt(variance)) + 0.5))));
}

// aerodynamic_drag — Aerodynamic drag force magnitude on a surface panel. Multiply result by surface normal for force vector.
// source: Classical aerodynamics; matches cloth_simulator.cpp implementation   R²: 1
float aerodynamicDrag(float vDotN, float surfaceArea, float airDensity)
{
    return (0.5 * (0.47 * (airDensity * (surfaceArea * vDotN))));
}

// beer_lambert — Beer-Lambert absorption law. Models exponential light attenuation through a medium (water, fog).
// source: Beer-Lambert law; matches water.frag.glsl absorption   R²: 1
float beerLambert(float I0, float depth)
{
    return (I0 * exp((-(0.40000001 * depth))));
}

// bloom_threshold — Soft bloom threshold extraction with knee curve. Produces smooth transition instead of hard cutoff.
// source: Soft bloom knee from Karis 2014 (UE4 bloom); common in post-processing   R²: 1
float bloomThreshold(float luminance)
{
    return safeDiv(max(0.0, (luminance - 1.0)), ((luminance - 1.0) + 0.5));
}

// buoyancy — Archimedes buoyancy force magnitude. Returns upward force on a partially or fully submerged object.
// source: Archimedes' principle; matches environment_forces.cpp buoyancy   R²: 1
float buoyancy(float fluidDensity, float submergedVolume)
{
    return (fluidDensity * (submergedVolume * 9.8100004));
}

// caustic_depth_fade — Caustic intensity fade with depth below water surface. Returns 1.0 at surface, 0.0 at maxDepth.
// source: Matches scene.frag.glsl smoothstep(0, 5, depthBelowWater) depth fade   R²: 1
float causticDepthFade(float depth, float maxDepth)
{
    return (1.0 - ((clamp(safeDiv(depth, maxDepth), 0.0, 1.0) * clamp(safeDiv(depth, maxDepth), 0.0, 1.0)) * (3.0 - (2.0 * clamp(safeDiv(depth, maxDepth), 0.0, 1.0)))));
}

// cosine_hemisphere_pdf — Cosine-weighted hemisphere sampling PDF for a diffuse bounce: pdf = cosTheta / pi (1/pi encoded as a literal; the AST has no pi constant). Upper hemisphere only — the caller masks cosTheta < 0 (PDF is 0 there).
// source: Pharr, Jakob & Humphreys, Physically Based Rendering 4th ed (2023), App. A.5.3 — pdf = cosTheta/pi.   R²: 1
float cosineHemispherePdf(float cosTheta)
{
    return (cosTheta * 0.3183099);
}

// coulomb_friction — Coulomb friction model. Clamps tangential force to mu * normal_force. Returns the clamped tangential force.
// source: Coulomb friction; matches cloth_simulator.h friction model   R²: 1
float coulombFriction(float Ft, float Fn)
{
    return min(Ft, (0.5 * Fn));
}

// dof_coc — Circle of confusion (CoC) diameter for depth of field. Returns the blur disk size for a given depth.
// source: Thin-lens CoC equation; standard depth of field model   R²: 1
float dofCoc(float depth)
{
    return abs(safeDiv((2.8 * (0.050000001 * (5.0 - depth))), (depth * (5.0 - 0.050000001))));
}

// ease_in_sine — Penner easeInSine easing function. Slow start using cosine. Compare FULL (trig) vs APPROXIMATE (polynomial) in the workbench.
// source: Robert Penner easing equations; matches easing.cpp easeInSine()   R²: 1
float easeInSine(float t)
{
    return (1.0 - cos((t * 1.5707963)));
}

// edge_stopping_depth — SVGF depth edge-stopping weight: w_z = exp(-|dz| / (sigmaZ*gradTerm + eps)). dz = |z_p - z_q|, gradTerm = |grad(z)·(p-q)|. Re-fit sigmaZ.
// source: Schied et al. 2017, Eq. 3.   R²: 1
float edgeStoppingDepth(float dz, float gradTerm)
{
    return exp((-safeDiv(dz, ((1.0 * gradTerm) + 0.001))));
}

// edge_stopping_luminance — SVGF luminance edge-stopping weight: w_l = exp(-|dl| / (sigmaL*sqrt(gVar) + eps)). dl = |l_p - l_q|, gVar = 3x3-Gaussian-prefiltered luminance variance. Re-fit sigmaL (paper uses 4).
// source: Schied et al. 2017, Eq. 5.   R²: 1
float edgeStoppingLuminance(float dl, float gVar)
{
    return exp((-safeDiv(dl, ((4.0 * safeSqrt(gVar)) + 0.001))));
}

// edge_stopping_normal — SVGF normal edge-stopping weight: w_n = pow(max(0, n_p·n_q), sigmaN). Re-fit sigmaN (paper uses 128).
// source: Schied et al. 2017, Eq. 4.   R²: 1
float edgeStoppingNormal(float ndot)
{
    return safePow(max(0.0, ndot), 128.0);
}

// exponential_fog — Exponential fog visibility factor. Returns [0,1] where 0 is fully fogged and 1 is fully clear.
// source: Exponential fog model; common in real-time rendering   R²: 1
float exponentialFog(float distance)
{
    return exp((-(0.0099999998 * distance)));
}

// exposure_ev — EV-based exposure multiplier. Converts exposure value to a linear multiplier for HDR rendering. 1.2 = middle-grey calibration.
// source: Standard EV exposure model; matches camera exposure calculations   R²: 1
float exposureEv(float ev)
{
    return safeDiv(1.0, (safePow(2.0, ev) * 1.2));
}

// fast_neg_exp — Negative exponential and its fast rational polynomial approximation. Used in spring-damper trajectory prediction. APPROXIMATE: Holden's rational polynomial (no exp() call).
// source: Daniel Holden 'Spring-It-On' (2020); matches trajectory_predictor.cpp fastNegexp()   R²: 1
float fastNegExp(float x)
{
    return exp((-x));
}

// fresnel_schlick — Schlick approximation of Fresnel reflectance. F0=0.02 for water (n=1.33).
// source: Schlick 1994; matches water.frag.glsl implementation   R²: 1
float fresnelSchlick(float cosTheta)
{
    return (0.02 + ((1.0 - 0.02) * safePow((1.0 - cosTheta), 5.0)));
}

// gerstner_wave — Single Gerstner wave displacement (vertical component). Sum multiple waves for realistic water surface.
// source: Gerstner wave equation; matches water_surface.h Wave config   R²: 1
float gerstnerWave(float x, float t)
{
    return (0.5 * sin((((1.0 * x) - (1.0 * t)) + 0.0)));
}

// ggx_distribution — GGX / Trowbridge-Reitz normal distribution function (NDF). Core of the Cook-Torrance specular BRDF. alpha = roughness^2.
// source: GGX (Trowbridge-Reitz 1975, Walter et al. 2007); matches scene.frag.glsl distributionGGX()   R²: 1
float ggxDistribution(float NdotH)
{
    return safeDiv(safePow(0.25, 2.0), (3.1415927 * safePow(((safePow(NdotH, 2.0) * (safePow(0.25, 2.0) - 1.0)) + 1.0), 2.0)));
}

// ggx_vndf_pdf — GGX visible-normal (VNDF) sampling PDF of the reflected direction: pdf(L) = G1 * D / (4 * NdotV). Reflection lobe, single-scattering, isotropic. Supply G1 (Smith masking for V) and D (GGX NDF at H) from the shipped schlick_geometry / ggx_distribution templates. Roughness remap alpha = perceptualRoughness^2 is the caller's.
// source: Heitz, 'Sampling the GGX Distribution of Visible Normals', JCGT 7(4) 2018 (D_visible, Eq. 3); Walter et al., EGSR 2007 (reflection Jacobian 1/(4|V·H|)).   R²: 1
float ggxVndfPdf(float G1, float D, float NdotV)
{
    return safeDiv((G1 * D), (4.0 * NdotV));
}

// height_blend — Height-based texture blending for terrain. Produces more natural transitions than linear blending by using height data.
// source: Height-based blending from GPU Gems 3; common terrain rendering technique   R²: 1
float heightBlend(float heightA, float heightB, float blendFactor)
{
    return clamp(safeDiv(((heightA - heightB) + blendFactor), 0.1), 0.0, 1.0);
}

// hooke_spring — Hooke's law spring force. Negative sign indicates restoring force toward rest length.
// source: Hooke's law; used in cloth XPBD solver distance constraints   R²: 1
float hookeSpring(float x, float restLength)
{
    return (-(100.0 * (x - restLength)));
}

// inverse_square_falloff — Light attenuation with configurable constant, linear, and quadratic terms. Standard OpenGL attenuation model.
// source: Standard OpenGL attenuation; matches scene.frag.glsl   R²: 1
float inverseSquareFalloff(float distance)
{
    return safeDiv(1.0, (1.0 + ((0.090000004 * distance) + (0.032000002 * safePow(distance, 2.0)))));
}

// linear_to_srgb — linear → sRGB encode (one channel, [0,1]). FULL: c <= 0.0031308 ? 12.92*c : 1.055*pow(c, 1/2.4) - 0.055. APPROXIMATE: pow(c, 1/2.2). Predicate max(0, 0.0031308-c) is nonzero (true) for c < 0.0031308.
// source: IEC 61966-2-1:1999; exponent 1/2.4 = 0.41666….   R²: 1
float linearToSrgb(float c)
{
    return (max(0.0, (0.0031308001 - c)) != 0.0 ? (12.92 * c) : ((1.0549999 * safePow(c, 0.41666666)) - 0.055));
}

// mis_power_heuristic — Multiple-importance-sampling weight for two strategies (single sample each). FULL: power heuristic beta=2, w = pdfA^2 / (pdfA^2 + pdfB^2). APPROXIMATE: balance heuristic, w = pdfA / (pdfA + pdfB). The two strategies' weights sum to 1; vanishes where pdfA is 0.
// source: Veach & Guibas, 'Optimally Combining Sampling Techniques for Monte Carlo Rendering', SIGGRAPH '95, Eq. 14 (power), §3.3 (balance).   R²: 1
float misPowerHeuristic(float pdfA, float pdfB)
{
    return safeDiv(safePow(pdfA, 2.0), (safePow(pdfA, 2.0) + safePow(pdfB, 2.0)));
}

// rr_survival — Russian-roulette path survival probability: p = clamp(maxThroughput, pMin, pMax). Common engine variant (max-channel + two-sided clamp). PBRT §14.5.4 uses luminance + a single floor q=max(0.05,1-lum). RR stays unbiased but adds variance — apply only after early bounces (e.g. depth > 3). Survivors rescale throughput by 1/p (caller's job). maxThroughput = max(throughput.rgb) is a vec3 reduction outside the AST.
// source: Arvo & Kirk, 'Particle Transport and Image Synthesis', SIGGRAPH '90; PBRT §13.7 / §14.5.4 (PBRT form differs — see description).   R²: 1
float rrSurvival(float maxThroughput)
{
    return min(0.94999999, max(0.050000001, maxThroughput));
}

// schlick_geometry — Schlick-GGX geometry function (one side of Smith's method). k=(roughness+1)^2/8 for direct, k=roughness^2/2 for IBL.
// source: Schlick 1994, applied to GGX (Karis 2013); matches scene.frag.glsl geometrySchlickGGX()   R²: 1
float schlickGeometry(float NdotV)
{
    return safeDiv(NdotV, ((NdotV * (1.0 - 0.125)) + 0.125));
}

// spot_cone_falloff — Spot light cone intensity falloff. Returns 1.0 inside the inner cone, 0.0 outside the outer cone, smooth blend between.
// source: Standard spot light model; matches scene.frag.glsl spot calculation   R²: 1
float spotConeFalloff(float theta)
{
    return clamp(safeDiv((theta - 0.90630001), (0.9659 - 0.90630001)), 0.0, 1.0);
}

// srgb_to_linear — sRGB → linear decode (one channel, [0,1]). FULL: c <= 0.04045 ? c/12.92 : pow((c+0.055)/1.055, 2.4). APPROXIMATE: pow(c, 2.2). Predicate max(0, 0.04045-c) is nonzero (true) for c < 0.04045; the equality point lands on the high branch, matching the standard's > boundary.
// source: IEC 61966-2-1:1999; W3C CSS Color 4 reference code. Rounded breakpoint 0.04045 (= 12.92·0.0031308). Not perfectly C1 / not an exact inverse of the encode — use rounded IEC constants.   R²: 1
float srgbToLinear(float c)
{
    return (max(0.0, (0.040449999 - c)) != 0.0 ? safeDiv(c, 12.92) : safePow(safeDiv((c + 0.055), 1.0549999), 2.4000001));
}

// stokes_drag — Stokes drag for small spherical particles at low Reynolds number. Valid for dust, rain drops, small debris.
// source: Stokes' law (1851); valid for Re < 1   R²: 1
float stokesDrag(float velocity, float radius)
{
    return (6.0 * (3.1415927 * (1.810000e-05 * (radius * velocity))));
}

// temporal_alpha — Temporal exponential-moving-average blend factor with a floor: alpha = max(aMin, 1/(n+1)). n is the accumulated history length; at n=0 alpha=1 (full reset on a disocclusion). Re-fit aMin to taste (SVGF uses 0.2).
// source: Schied et al., 'Spatiotemporal Variance-Guided Filtering', HPG '17, §4.1 (temporal integration; disocclusion → alpha=1).   R²: 1
float temporalAlpha(float n)
{
    return max(0.2, safeDiv(1.0, (n + 1.0)));
}

// terminal_velocity — Terminal velocity of a falling object in a fluid. Balances gravitational and drag forces.
// source: Derived from drag equation equilibrium with gravity   R²: 1
float terminalVelocity(float mass, float area, float airDensity)
{
    return safeSqrt(safeDiv((2.0 * (mass * 9.8100004)), (airDensity * (area * 0.47))));
}

// thermal_erosion — Thermal erosion sediment transfer rate. Models material sliding down slopes that exceed the talus angle.
// source: Musgrave 1989 thermal erosion model; common in procedural terrain generation   R²: 1
float thermalErosion(float slope, float dt)
{
    return (0.5 * (max(0.0, (slope - 0.57700002)) * dt));
}

// vignette — Radial vignette darkening effect. Returns a multiplier [0,1] that darkens pixels further from screen center.
// source: Standard vignette post-processing effect   R²: 1
float vignette(float distance)
{
    return (1.0 - (0.5 * safePow(distance, 2.0)));
}

// water_absorption — Per-channel water light absorption (Beer-Lambert). Red light absorbed fastest (0.4), green medium (0.2), blue slowest (0.1). Apply per-channel in shader.
// source: Beer-Lambert with water-specific coefficients from water.frag.glsl   R²: 1
float waterAbsorption(float thickness, float absorptionCoeff)
{
    return exp((-(absorptionCoeff * thickness)));
}

// wet_darkening — Wet surface albedo darkening. Wet surfaces appear darker due to total internal reflection trapping light.
// source: Common PBR technique; physically based on Snell/Fresnel at water-surface interface   R²: 1
float wetDarkening(float albedo, float wetness)
{
    return (albedo * (1.0 - (wetness * 0.5)));
}

// wind_deformation — Wind-driven bending displacement for vegetation. Height-squared gives realistic base-anchored deformation.
// source: GPU Gems 3 Ch.6 vegetation animation   R²: 1
float windDeformation(float windSpeed, float flexibility, float height)
{
    return (windSpeed * (flexibility * safePow(height, 2.0)));
}

