// Emacs style mode select   -*- C++ -*- 
//-----------------------------------------------------------------------------
//
// $Id:$
//
// Copyright (C) 1993-1996 by id Software, Inc.
//
// This source is available for distribution and/or modification
// only under the terms of the DOOM Source Code License as
// published by id Software. All rights reserved.
//
// The source is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// FITNESS FOR A PARTICULAR PURPOSE. See the DOOM Source Code License
// for more details.
//
// $Log:$
//
// DESCRIPTION:
//	DOOM main program (D_DoomMain) and game loop (D_DoomLoop),
//	plus functions to determine game mode (shareware, registered),
//	parse command line parameters, configure game parameters (turbo),
//	and call the startup functions.
//
//-----------------------------------------------------------------------------


static const char rcsid[] __attribute__((used)) = "$Id: d_main.c,v 1.8 1997/02/03 22:45:09 b1 Exp $";

#define	BGCOLOR		7
#define	FGCOLOR		8


#ifdef NORMALUNIX
#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#endif

#include <limits.h>		// PATH_MAX (used outside the NORMALUNIX guard)
#include <errno.h>		// DOOM-0060 relaunch error reporting

#ifdef _WIN32
#define WIN32_LEAN_AND_MEAN	// exclude <rpcndr.h>, which typedefs `boolean`
				// (unsigned char) and clashes with doomtype.h's
				// `typedef enum {false,true} boolean`
#include <windows.h>		// GetModuleFileNameA (DOOM-0060 relaunch)
#include <process.h>		// _spawnv / _P_NOWAIT
#endif

#include "doomdef.h"
#include "doomstat.h"
#include "iwad_detect.h"	// DOOM-0060 game-select: pure IWAD-family classifier

#include "dstrings.h"
#include "sounds.h"


#include "z_zone.h"
#include "w_wad.h"
#include "s_sound.h"
#include "v_video.h"

#include "f_finale.h"
#include "f_wipe.h"

#include "m_argv.h"
#include "m_misc.h"
#include "m_menu.h"

#include "i_system.h"
#include "i_sound.h"
#include "i_video.h"

#include "g_game.h"

#include "hu_stuff.h"
#include "wi_stuff.h"
#include "st_stuff.h"
#include "am_map.h"

#include "p_setup.h"
#include "r_local.h"
#include "r_backend.h"


#include "d_main.h"

//
// D-DoomLoop()
// Not a globally visible function,
//  just included for source reference,
//  called by D_DoomMain, never exits.
// Manages timing and IO,
//  calls all ?_Responder, ?_Ticker, and ?_Drawer,
//  calls I_GetTime, I_StartFrame, and I_StartTic
//
void D_DoomLoop (void);


char*		wadfiles[MAXWADFILES];


boolean		devparm;	// started game with -devparm
boolean         nomonsters;	// checkparm of -nomonsters
boolean         respawnparm;	// checkparm of -respawn
boolean         fastparm;	// checkparm of -fast

boolean         drone;

boolean		singletics = false; // debug flag to cancel adaptiveness



//extern int soundVolume;
//extern  int	sfxVolume;
//extern  int	musicVolume;

extern  boolean	inhelpscreens;

skill_t		startskill;
int             startepisode;
int		startmap;
boolean		autostart;

FILE*		debugfile;

boolean		advancedemo;




char		wadfile[1024];		// primary wad file
char		mapdir[1024];           // directory of development maps
char		basedefault[1024];      // default file


void D_CheckNetGame (void);
void D_ProcessEvents (void);
void G_BuildTiccmd (ticcmd_t* cmd);
void D_DoAdvanceDemo (void);


//
// EVENT HANDLING
//
// Events are asynchronous inputs generally generated by the game user.
// Events can be discarded if no responder claims them
//
event_t         events[MAXEVENTS];
int             eventhead;
int 		eventtail;


//
// D_PostEvent
// Called by the I/O functions when input is detected
//
void D_PostEvent (event_t* ev)
{
    events[eventhead] = *ev;
    eventhead = (eventhead + 1)&(MAXEVENTS-1);
}


//
// D_ProcessEvents
// Send all the events of the given timestamp down the responder chain
//
void D_ProcessEvents (void)
{
    event_t*	ev;
	
    // IF STORE DEMO, DO NOT ACCEPT INPUT
    if ( ( gamemode == commercial )
	 && (W_CheckNumForName("map01")<0) )
      return;
	
    for ( ; eventtail != eventhead ; eventtail = (eventtail + 1)&(MAXEVENTS-1) )
    {
	ev = &events[eventtail];
	if (M_Responder (ev))
	    continue;               // menu ate the event
	G_Responder (ev);
    }
}




//
// D_Display
//  draw current display, possibly wiping it from the previous
//

// wipegamestate can be set to -1 to force a wipe on the next draw
gamestate_t     wipegamestate = GS_DEMOSCREEN;
extern  boolean setsizeneeded;
extern  int             showMessages;
void R_ExecuteSetViewSize (void);

void D_Display (void)
{
    static  boolean		viewactivestate = false;
    static  boolean		menuactivestate = false;
    static  boolean		inhelpscreensstate = false;
    static  boolean		fullscreen = false;
    static  gamestate_t		oldgamestate = -1;
    static  int			borderdrawcount;
    int				nowtime;
    int				tics;
    int				wipestart;
    int				y;
    boolean			done;
    boolean			wipe;
    boolean			redrawsbar;

    if (nodrawers)
	return;                    // for comparative timing / profiling
		
    redrawsbar = false;

    // change the view size if needed
    if (setsizeneeded)
    {
	R_ExecuteSetViewSize ();
	oldgamestate = -1;                      // force background redraw
	borderdrawcount = 3;
    }

    // save the current screen if about to wipe
    if (gamestate != wipegamestate)
    {
	wipe = true;
	wipe_StartScreen(0, 0, SCREENWIDTH, SCREENHEIGHT);
    }
    else
	wipe = false;

    if (gamestate == GS_LEVEL && gametic)
	HU_Erase();
    
    // do buffered drawing
    switch (gamestate)
    {
      case GS_LEVEL:
	if (!gametic)
	    break;
	if (automapactive)
	    AM_Drawer ();
	if (wipe || (viewheight != 200 && fullscreen) )
	    redrawsbar = true;
	if (inhelpscreensstate && !inhelpscreens)
	    redrawsbar = true;              // just put away the help screen
	// In a 3D back-end the compositor reads the whole paletted screens[0]
	// each frame but only keys the 3D view rect transparent; the status-bar
	// region is otherwise only diff-drawn, so stale menu pixels painted over
	// it last frame are never erased and ghost through (DOOM-0050). Force a
	// full status-bar refresh in 3D so its background repaints and clears them.
	// Classic blits the whole screen, so it needs no force.
	// Force a full status-bar repaint in 3D (the compositor reads the whole
	// HUD each frame) and, in any mode, while a menu is or was just open --
	// otherwise menu text drawn over the status bar isn't erased when the
	// menu closes (DOOM-0053). This only repaints the HUD; it does NOT touch
	// the view-resize/border path that crashed earlier (DOOM-0055).
	ST_Drawer (viewheight == 200,
		   redrawsbar || rendermode != RB_CLASSIC
		   || menuactive || menuactivestate);
	fullscreen = viewheight == 200;
	break;

      case GS_INTERMISSION:
	WI_Drawer ();
	break;

      case GS_FINALE:
	F_Drawer ();
	break;

      case GS_DEMOSCREEN:
	D_PageDrawer ();
	break;
    }
    
    // draw buffered stuff to screen
    I_UpdateNoBlit ();
    
    // draw the view directly
    if (gamestate == GS_LEVEL && !automapactive && gametic)
	RB_RenderPlayerView (&players[displayplayer]);

    if (gamestate == GS_LEVEL && gametic)
	HU_Drawer ();
    
    // clean up border stuff
    if (gamestate != oldgamestate && gamestate != GS_LEVEL)
	I_SetPalette (W_CacheLumpName ("PLAYPAL",PU_CACHE));

    // see if the border needs to be initially drawn
    if (gamestate == GS_LEVEL && oldgamestate != GS_LEVEL)
    {
	viewactivestate = false;        // view was not active
	R_FillBackScreen ();    // draw the pattern into the back screen
    }

    // see if the border needs to be updated to the screen
    if (gamestate == GS_LEVEL && !automapactive && scaledviewwidth != 320)
    {
	if (menuactive || menuactivestate || !viewactivestate)
	    borderdrawcount = 3;
	if (borderdrawcount)
	{
	    R_DrawViewBorder ();    // erase old menu stuff
	    borderdrawcount--;
	}

    }

    menuactivestate = menuactive;
    viewactivestate = viewactive;
    inhelpscreensstate = inhelpscreens;
    oldgamestate = wipegamestate = gamestate;
    
    // draw pause pic.  viewwindowx/y and scaledviewwidth are physical; the
    // M_PAUSE patch draws through the logical-space V_DrawPatch, so divide the
    // geometry by HIRES (68 is the patch's logical width) (DOOM-0027).
    if (paused)
    {
	if (automapactive)
	    y = 4;
	else
	    y = viewwindowy/HIRES+4;
	V_DrawPatchDirect(viewwindowx/HIRES+(scaledviewwidth/HIRES-68)/2,
			  y,0,W_CacheLumpName ("M_PAUSE", PU_CACHE));
    }


    // optional FPS counter (DOOM-0046): drawn into screens[0] each frame, in
    // every gamestate, so it composites under every renderer. Under the menu.
    HU_DrawFPS ();

    // menus go directly to the screen
    M_Drawer ();          // menu is drawn even on top of everything
    NetUpdate ();         // send out any new accumulation


    // normal update
    if (!wipe)
    {
	RB_Present ();                  // page flip or blit buffer
	return;
    }
    
    // wipe update
    wipe_EndScreen(0, 0, SCREENWIDTH, SCREENHEIGHT);

    wipestart = I_GetTime () - 1;

    do
    {
	do
	{
	    nowtime = I_GetTime ();
	    tics = nowtime - wipestart;
	} while (!tics);
	wipestart = nowtime;
	done = wipe_ScreenWipe(wipe_Melt
			       , 0, 0, SCREENWIDTH, SCREENHEIGHT, tics);
	I_UpdateNoBlit ();
	M_Drawer ();                            // menu is drawn even on top of wipes
	RB_Present ();                          // page flip or blit buffer
    } while (!done);
}



//
//  D_DoomLoop
//
extern  boolean         demorecording;

// DOOM-0203: >0 when the headless CI boot-smoke (`-bootsmoke [N]`) is armed; the
// number of game tics to simulate before exiting 0. Set in D_DoomMain.
static int              bootsmoke_tics = 0;

void D_DoomLoop (void)
{
    if (demorecording)
	G_BeginRecording ();
		
    if (M_CheckParm ("-debugfile"))
    {
	char    filename[20];
	sprintf (filename,"debug%i.txt",consoleplayer);
	printf ("debug output to: %s\n",filename);
	debugfile = fopen (filename,"w");
    }
	
    I_InitGraphics ();

    // DOOM-0203: the headless CI boot-smoke runs on a GPU-less runner. Pin the
    // software renderer so a stray software Vulkan ICD (e.g. lavapipe) can't pull
    // us onto the GPU path that has no device to render on.
    if (bootsmoke_tics > 0)
	rendermode = RB_CLASSIC;

    // Pick + init the renderer back-end now the SDL/graphics device exists,
    // so a back-end's Available()/Init() can probe the GPU (DOOM-0026).
    RB_Init ();

    int bootsmokeStart = gametic;   // DOOM-0203: baseline for the tic countdown

    while (1)
    {
	// frame syncronous IO operations
	I_StartFrame ();

	// DOOM-0048: in single-player 3D, decouple the present rate from the 35 Hz
	// game tic. Run every tic that is due without blocking, then render an
	// interpolated in-between frame paced by vsync, so the camera is smooth above
	// 35 FPS while the simulation stays locked to 35 Hz. Net/demo/Classic keep the
	// classic tic-locked path (sync + demo determinism + no wasted software redraws).
	static boolean wasUncapped = false;
	static int     lastTicMs   = 0;
	boolean uncapped = !singletics && !netgame && !demoplayback
			 && !demorecording && rendermode != RB_CLASSIC;
	int ticBefore = gametic;

	// process one or more tics
	if (singletics)
	{
	    I_StartTic ();
	    D_ProcessEvents ();
	    G_BuildTiccmd (&netcmds[consoleplayer][maketic%BACKUPTICS]);
	    if (advancedemo)
		D_DoAdvanceDemo ();
	    M_Ticker ();
	    G_Ticker ();
	    gametic++;
	    maketic++;
	}
	else if (uncapped)
	{
	    // Non-blocking equivalent of TryRunTics for one node: NetUpdate() reads
	    // input and advances maketic at 35 Hz; run each available tic, capped at
	    // a second so a long stall can't spiral.
	    int guard = 0;
	    NetUpdate ();
	    while (gametic < maketic && guard++ < TICRATE)
	    {
		if (advancedemo)
		    D_DoAdvanceDemo ();
		M_Ticker ();
		G_Ticker ();
		gametic++;
	    }
	}
	else
	{
	    TryRunTics (); // will run at least one tic
	}

	// Drive the render interpolation (DOOM-0048). Reset on entry so a stale frame
	// can't smear; snapshot when a tic ran; set the sub-tic fraction every frame.
	if (uncapped)
	{
	    player_t* vp = &players[consoleplayer];
	    if (!wasUncapped)
		RB_InterpReset (vp);
	    if (gametic != ticBefore)
	    {
		RB_InterpSnapshot (vp);
		lastTicMs = I_GetTimeMS ();
	    }
	    RB_InterpSetFrac ((double)(I_GetTimeMS () - lastTicMs) / (1000.0 / TICRATE));
	}
	else
	{
	    RB_InterpDisable ();
	}
	wasUncapped = uncapped;

	S_UpdateSounds (players[consoleplayer].mo);// move positional sounds

	// Update display, next frame, with current state.
	D_Display ();

	// DOOM-0203: headless boot-smoke — once N tics have simulated (world stepped
	// + software renderer drew each frame without crashing), the engine has proven
	// it boots and renders; exit cleanly (0). Unlike -timedemo, no demo lump and
	// no I_Error timing report, so a passing run is exit 0.
	if (bootsmoke_tics > 0 && gametic - bootsmokeStart >= bootsmoke_tics)
	{
	    printf ("bootsmoke: %d tics simulated OK, exiting.\n",
		    gametic - bootsmokeStart);
	    I_Quit ();
	}

#ifndef SNDSERV
	// Sound mixing for the buffer is snychronous.
	I_UpdateSound();
#endif	
	// Synchronous sound output is explicitly called.
#ifndef SNDINTR
	// Update sound output.
	I_SubmitSound();
#endif
    }
}



//
//  DEMO LOOP
//
int             demosequence;
int             pagetic;
char                    *pagename;


//
// D_PageTicker
// Handles timing for warped projection
//
void D_PageTicker (void)
{
    // DOOM-0152: freeze the attract cycle while the menu is up, so the background
    // doesn't slide from the title to the red-on-red CREDIT/HELP page (or a demo)
    // behind the menu and make the menu text illegible.
    if (menuactive)
	return;
    if (--pagetic < 0)
	D_AdvanceDemo ();
}



//
// D_PageDrawer
//
void D_PageDrawer (void)
{
    // DOOM-0152: with the menu open, always show the plain TITLEPIC behind it. The
    // attract loop's CREDIT/HELP pages are dense red text the (red) menu items are
    // illegible over; paired with D_PageTicker's freeze so the page stays put.
    V_DrawPatch (0,0, 0,
		 W_CacheLumpName(menuactive ? "TITLEPIC" : pagename, PU_CACHE));
    V_ExtendSides (0);		// DOOM-0151: fill widescreen side strips (no-op at 4:3)
}


//
// D_AdvanceDemo
// Called after each demo or intro demosequence finishes
//
void D_AdvanceDemo (void)
{
    advancedemo = true;
}


//
// This cycles through the demo sequences.
// FIXME - version dependend demo numbers?
//
 void D_DoAdvanceDemo (void)
{
    players[consoleplayer].playerstate = PST_LIVE;  // not reborn
    advancedemo = false;
    usergame = false;               // no save / end game here
    paused = false;
    gameaction = ga_nothing;

    if ( gamemode == retail )
      demosequence = (demosequence+1)%7;
    else
      demosequence = (demosequence+1)%6;
    
    switch (demosequence)
    {
      case 0:
	if ( gamemode == commercial )
	    pagetic = 35 * 11;
	else
	    pagetic = 170;
	gamestate = GS_DEMOSCREEN;
	pagename = "TITLEPIC";
	if ( gamemode == commercial )
	  S_StartMusic(mus_dm2ttl);
	else
	  S_StartMusic (mus_intro);
	break;
      case 1:
	G_DeferedPlayDemo ("demo1");
	break;
      case 2:
	pagetic = 200;
	gamestate = GS_DEMOSCREEN;
	pagename = "CREDIT";
	break;
      case 3:
	G_DeferedPlayDemo ("demo2");
	break;
      case 4:
	gamestate = GS_DEMOSCREEN;
	if ( gamemode == commercial)
	{
	    pagetic = 35 * 11;
	    pagename = "TITLEPIC";
	    S_StartMusic(mus_dm2ttl);
	}
	else
	{
	    pagetic = 200;

	    if ( gamemode == retail )
	      pagename = "CREDIT";
	    else
	      pagename = "HELP2";
	}
	break;
      case 5:
	G_DeferedPlayDemo ("demo3");
	break;
        // THE DEFINITIVE DOOM Special Edition demo
      case 6:
	G_DeferedPlayDemo ("demo4");
	break;
    }
}



//
// D_StartTitle
//
void D_StartTitle (void)
{
    gameaction = ga_nothing;
    demosequence = -1;
    D_AdvanceDemo ();
}




//      print title for every printed line
char            title[128];



//
// D_AddFile
//
void D_AddFile (char *file)
{
    int     numwadfiles;
    char    *newfile;
	
    for (numwadfiles = 0 ; wadfiles[numwadfiles] ; numwadfiles++)
	;

    newfile = malloc (strlen(file)+1);
    if (!newfile)
	I_Error ("D_AddFile: out of memory adding %s", file);
    strcpy (newfile, file);
	
    wadfiles[numwadfiles] = newfile;
}

// DOOM-0060: infer gamemode from an IWAD filename. Shared by the -iwad path and
// the remembered-last-game path.
static GameMode_t D_InferGamemode (const char* iwadpath)
{
    const char* base = strrchr(iwadpath, '/');
    base = base ? base + 1 : iwadpath;
    if (strstr(base,"doom2") || strstr(base,"tnt") || strstr(base,"plutonia"))
	return commercial;
    if (strstr(base,"doom1"))
	return shareware;
    if (strstr(base,"doomu"))
	return retail;
    return registered;
}

// DOOM-0060 "remember last game": the app records which IWAD it last loaded in
// $HOME/.doom_ants_lastgame and defaults to it on the next launch, instead of the
// doom2.wad-first auto-detect. Best-effort — a missing/unreadable file, a
// read-only HOME, or a stored path that no longer exists all fall back cleanly.
static void D_LastGameFile (char* out, size_t n)
{
    const char* home = getenv("HOME");
#ifdef _WIN32
    if (!home) home = getenv("USERPROFILE");
#endif
    if (!home) home = ".";
    snprintf(out, n, "%s/.doom_ants_lastgame", home);
}

static int D_ReadLastGame (char* out, size_t n)
{
    char	file[PATH_MAX];
    FILE*	f;
    size_t	len;

    D_LastGameFile(file, sizeof(file));
    f = fopen(file, "r");
    if (!f)
	return 0;
    if (!fgets(out, (int)n, f)) { fclose(f); return 0; }
    fclose(f);
    len = strlen(out);
    while (len > 0 && (out[len-1] == '\n' || out[len-1] == '\r' || out[len-1] == ' '))
	out[--len] = '\0';
    return out[0] != '\0';
}

static void D_WriteLastGame (const char* iwadpath)
{
    char	file[PATH_MAX];
    FILE*	f;

    if (!iwadpath || !iwadpath[0])
	return;
    D_LastGameFile(file, sizeof(file));
    f = fopen(file, "w");
    if (!f)
	return;                 // read-only HOME etc. -> remembering is simply off
    fprintf(f, "%s\n", iwadpath);
    fclose(f);
}

//
// IdentifyVersion
// Checks availability of IWAD files by name,
// to determine whether registered/commercial features
// should be executed (notably loading PWAD's).
//
void IdentifyVersion (void)
{

    // Fixed-size scratch buffers for the candidate IWAD paths. A path that
    // would not fit in PATH_MAX can't name a real file anyway, so snprintf
    // truncation is harmless - and stack buffers can't leak the way the old
    // per-candidate malloc()s did on every early return.
    char	doom1wad[PATH_MAX];
    char	doomwad[PATH_MAX];
    char	doomuwad[PATH_MAX];
    char	doom2wad[PATH_MAX];

    char	doom2fwad[PATH_MAX];
    char	plutoniawad[PATH_MAX];
    char	tntwad[PATH_MAX];

#ifdef NORMALUNIX
    char *home;
    char *doomwaddir;
    doomwaddir = getenv("DOOMWADDIR");
    if (!doomwaddir)
	doomwaddir = ".";

    // Commercial.
    snprintf(doom2wad, sizeof(doom2wad), "%s/doom2.wad", doomwaddir);

    // Retail.
    snprintf(doomuwad, sizeof(doomuwad), "%s/doomu.wad", doomwaddir);

    // Registered.
    snprintf(doomwad, sizeof(doomwad), "%s/doom.wad", doomwaddir);

    // Shareware.
    snprintf(doom1wad, sizeof(doom1wad), "%s/doom1.wad", doomwaddir);

    snprintf(plutoniawad, sizeof(plutoniawad), "%s/plutonia.wad", doomwaddir);

    snprintf(tntwad, sizeof(tntwad), "%s/tnt.wad", doomwaddir);


    // French stuff.
    snprintf(doom2fwad, sizeof(doom2fwad), "%s/doom2f.wad", doomwaddir);

    home = getenv("HOME");
#ifdef _WIN32
    if (!home)
      home = getenv("USERPROFILE");	// Windows has no $HOME (DOOM-0006)
#endif
    if (!home)
      I_Error("Please set $HOME to your home directory");
    snprintf(basedefault, sizeof(basedefault), "%s/.doomrc", home);
#endif

    // DOOM_Ants: -iwad <file> selects the IWAD explicitly, so DOOM 1 and
    // DOOM 2 can share one folder instead of relying on the doom2.wad-first
    // auto-search. gamemode is inferred from the filename; a registered
    // doom.wad is promoted to retail after load if it carries episode 4.
    {
	int iwadparm = M_CheckParm("-iwad");
	if (iwadparm && iwadparm < myargc-1)
	{
	    char* iwad = myargv[iwadparm+1];
	    gamemode = D_InferGamemode(iwad);
	    D_AddFile (iwad);
	    return;
	}
    }

    if (M_CheckParm ("-shdev"))
    {
	gamemode = shareware;
	devparm = true;
	D_AddFile (DEVDATA"doom1.wad");
	D_AddFile (DEVMAPS"data_se/texture1.lmp");
	D_AddFile (DEVMAPS"data_se/pnames.lmp");
	strcpy (basedefault,DEVDATA"default.cfg");
	return;
    }

    if (M_CheckParm ("-regdev"))
    {
	gamemode = registered;
	devparm = true;
	D_AddFile (DEVDATA"doom.wad");
	D_AddFile (DEVMAPS"data_se/texture1.lmp");
	D_AddFile (DEVMAPS"data_se/texture2.lmp");
	D_AddFile (DEVMAPS"data_se/pnames.lmp");
	strcpy (basedefault,DEVDATA"default.cfg");
	return;
    }

    if (M_CheckParm ("-comdev"))
    {
	gamemode = commercial;
	devparm = true;
	/* I don't bother
	if(plutonia)
	    D_AddFile (DEVDATA"plutonia.wad");
	else if(tnt)
	    D_AddFile (DEVDATA"tnt.wad");
	else*/
	    D_AddFile (DEVDATA"doom2.wad");
	    
	D_AddFile (DEVMAPS"cdata/texture1.lmp");
	D_AddFile (DEVMAPS"cdata/pnames.lmp");
	strcpy (basedefault,DEVDATA"default.cfg");
	return;
    }

    // DOOM-0060: prefer the game the player last loaded (remembered across runs)
    // over the doom2-first auto-detect below. A stored path that no longer exists
    // just falls through to auto-detect.
    {
	char last[PATH_MAX];
	if (D_ReadLastGame(last, sizeof(last)) && !access(last, R_OK))
	{
	    gamemode = D_InferGamemode(last);
	    D_AddFile (last);
	    return;
	}
    }

    if ( !access (doom2fwad,R_OK) )
    {
	gamemode = commercial;
	// C'est ridicule!
	// Let's handle languages in config files, okay?
	language = french;
	printf("French version\n");
	D_AddFile (doom2fwad);
	return;
    }

    if ( !access (doom2wad,R_OK) )
    {
	gamemode = commercial;
	D_AddFile (doom2wad);
	return;
    }

    if ( !access (plutoniawad, R_OK ) )
    {
      gamemode = commercial;
      D_AddFile (plutoniawad);
      return;
    }

    if ( !access ( tntwad, R_OK ) )
    {
      gamemode = commercial;
      D_AddFile (tntwad);
      return;
    }

    if ( !access (doomuwad,R_OK) )
    {
      gamemode = retail;
      D_AddFile (doomuwad);
      return;
    }

    if ( !access (doomwad,R_OK) )
    {
      gamemode = registered;
      D_AddFile (doomwad);
      return;
    }

    if ( !access (doom1wad,R_OK) )
    {
      gamemode = shareware;
      D_AddFile (doom1wad);
      return;
    }

    // No IWAD found. Tell the user exactly what to do — the packaged builds
    // (Windows zip / Linux AppImage) have no room for a long readme, and the
    // game data is not redistributable, so this message is where most players
    // learn where the WAD goes (DOOM-0040).
    printf("No DOOM game data (IWAD) found in: %s\n", doomwaddir);
    printf("Put a .wad file (doom1.wad, doom.wad or doom2.wad) in that folder\n");
    printf("- next to the program - or run with: -iwad <path-to-your.wad>\n");
    printf("The free shareware doom1.wad works.\n");
    printf("Game mode indeterminate.\n");
    gamemode = indetermined;

    // We don't abort. Let's see what the PWAD contains.
    //exit(1);
    //I_Error ("Game mode indeterminate\n");
}

//
// DOOM-0060 game-select: detect installed IWADs + relaunch into the other game.
//
// D_DetectIwads records one representative path per family so the game-select
// chooser (m_menu.c) can offer both and relaunch into the other. The pure
// filename->family classification lives in iwad_detect.h (unit-tested); here we
// only do the directory scan (I/O) and the relaunch. Independent of which IWAD
// IdentifyVersion loaded. See docs/specs/DOOM-0060-game-select.md.
//
static char	iwadDoom1Path[PATH_MAX];
static char	iwadDoom2Path[PATH_MAX];
static boolean	iwadBothPresent;

// The "is it installed?" predicate iwad_select_reps calls: build <dir>/<name> and
// test it for readability. `ctx` is the WAD directory.
static int D_IwadPresent (const char* name, void* ctx)
{
    char path[PATH_MAX];

    snprintf(path, sizeof(path), "%s/%s", (const char*)ctx, name);
    return !access(path, R_OK);
}

void D_DetectIwads (void)
{
    // The preference-ordered scan itself lives in iwad_detect.h (iwad_select_reps)
    // so the unit test drives the same loop with an in-memory present-set instead
    // of a copy of it. Here we supply the I/O half and rebuild the directory paths
    // from the shared name list (the stack-local path buffers in IdentifyVersion
    // can't be reused).
    const char* dir = getenv("DOOMWADDIR");
    int d1, d2;

    if (!dir)
	dir = ".";
    iwadDoom1Path[0] = iwadDoom2Path[0] = '\0';

    iwad_select_reps(D_IwadPresent, (void*)dir, &d1, &d2);
    if (d1 >= 0)
	snprintf(iwadDoom1Path, PATH_MAX, "%s/%s", dir, IWAD_CANDIDATES[d1]);
    if (d2 >= 0)
	snprintf(iwadDoom2Path, PATH_MAX, "%s/%s", dir, IWAD_CANDIDATES[d2]);

    iwadBothPresent = (iwadDoom1Path[0] != '\0' && iwadDoom2Path[0] != '\0');
}

int D_BothGamesPresent (void)
{
    return iwadBothPresent;
}

const char* D_IwadPathForFamily (int family)
{
    return (family == IWAD_DOOM2) ? iwadDoom2Path : iwadDoom1Path;
}

// Relaunch the engine into a different IWAD in a fresh process (DOOM-0060's
// chosen approach: a clean boot sidesteps tearing down WAD-global state). The
// child gets an explicit -iwad, so it skips the game-select picker.
void D_RelaunchWithIwad (const char* iwadpath)
{
    char	exe[PATH_MAX];
    char*	newargv[4];

    // Resolve our own executable's real path -- myargv[0] may be a bare name
    // (found via $PATH) or a relative path that won't re-exec after a chdir.
    exe[0] = '\0';
#ifdef _WIN32
    if (GetModuleFileNameA(NULL, exe, sizeof(exe)) == 0)
	exe[0] = '\0';
#else
    {
	ssize_t n = readlink("/proc/self/exe", exe, sizeof(exe) - 1);
	if (n > 0)
	    exe[n] = '\0';
	else
	    exe[0] = '\0';
    }
#endif
    if (!exe[0])
    {
	if (myargv[0] && myargv[0][0])
	    snprintf(exe, sizeof(exe), "%s", myargv[0]);
	else
	    I_Error("game-select: cannot locate the engine executable to relaunch");
    }

    newargv[0] = exe;
    newargv[1] = "-iwad";
    newargv[2] = (char*)iwadpath;
    newargv[3] = NULL;

#ifdef _WIN32
    // The parent lingers after _spawnv, so release the window + audio device
    // first (the I_Quit teardown, which also saves config), then hand off. A
    // failed spawn must NOT fall through to exit(0) -- that would silently quit
    // the running game reporting success.
    I_QuitTeardown();
    // _spawnv takes a const char* const* argv; newargv is a plain char*[].
    if (_spawnv(_P_NOWAIT, exe, (const char* const*)newargv) < 0)
	I_Error("game-select: could not relaunch %s: %s", exe, strerror(errno));
    exit(0);
#else
    // execv replaces the process image; the kernel reclaims the window, GPU and
    // audio device with the old image, so only the config must be saved by hand
    // (atexit does not run across execv). execv returns only on failure.
    M_SaveDefaults();
    execv(exe, newargv);
    I_Error("game-select: relaunch failed: %s", strerror(errno));
#endif
}

//
// Find a Response File
//
void FindResponseFile (void)
{
    int             i;
#define MAXARGVS        100
	
    for (i = 1;i < myargc;i++)
	if (myargv[i][0] == '@')
	{
	    FILE *          handle;
	    int             size;
	    int             k;
	    int             index;
	    int             indexinfile;
	    char    *infile;
	    char    *file;
	    char    *moreargs[20];
	    char    *firstargv;
			
	    // READ THE RESPONSE FILE INTO MEMORY
	    handle = fopen (&myargv[i][1],"rb");
	    if (!handle)
	    {
		printf ("\nNo such response file!");
		exit(1);
	    }
	    printf("Found response file %s!\n",&myargv[i][1]);
	    fseek (handle,0,SEEK_END);
	    size = ftell(handle);
	    fseek (handle,0,SEEK_SET);
	    file = malloc (size);
	    if (!file)
		I_Error ("FindResponseFile: out of memory reading response file");
	    fread (file,size,1,handle);
	    fclose (handle);
			
	    // KEEP ALL CMDLINE ARGS FOLLOWING @RESPONSEFILE ARG
	    for (index = 0,k = i+1; k < myargc; k++)
		moreargs[index++] = myargv[k];
			
	    firstargv = myargv[0];
	    myargv = malloc(sizeof(char *)*MAXARGVS);
	    if (!myargv)
		I_Error ("FindResponseFile: out of memory rebuilding argv");
	    memset(myargv,0,sizeof(char *)*MAXARGVS);
	    myargv[0] = firstargv;
			
	    infile = file;
	    indexinfile = k = 0;
	    indexinfile++;  // SKIP PAST ARGV[0] (KEEP IT)
	    do
	    {
		myargv[indexinfile++] = infile+k;
		while(k < size &&
		      ((*(infile+k)>= ' '+1) && (*(infile+k)<='z')))
		    k++;
		*(infile+k) = 0;
		while(k < size &&
		      ((*(infile+k)<= ' ') || (*(infile+k)>'z')))
		    k++;
	    } while(k < size);
			
	    for (k = 0;k < index;k++)
		myargv[indexinfile++] = moreargs[k];
	    myargc = indexinfile;
	
	    // DISPLAY ARGS
	    printf("%d command-line args:\n",myargc);
	    for (k=1;k<myargc;k++)
		printf("%s\n",myargv[k]);

	    break;
	}
}


//
// D_DoomMain
//
void D_DoomMain (void)
{
    int             p;
    char                    file[256];

    FindResponseFile ();

    IdentifyVersion ();
    D_DetectIwads ();       // DOOM-0060: note which games are installed (for the chooser)
    // DOOM-0060: remember the game that just loaded, so the next launch defaults to
    // it instead of the doom2-first auto-detect. wadfiles[0] is the IWAD.
    if (gamemode != indetermined)
	D_WriteLastGame (wadfiles[0]);

    setbuf (stdout, NULL);
    modifiedgame = false;
	
    nomonsters = M_CheckParm ("-nomonsters");
    respawnparm = M_CheckParm ("-respawn");
    fastparm = M_CheckParm ("-fast");
    devparm = M_CheckParm ("-devparm");
    if (M_CheckParm ("-altdeath"))
	deathmatch = 2;
    else if (M_CheckParm ("-deathmatch"))
	deathmatch = 1;

    switch ( gamemode )
    {
      case retail:
	sprintf (title,
		 "                         "
		 "The Ultimate DOOM Startup v%i.%i"
		 "                           ",
		 VERSION/100,VERSION%100);
	break;
      case shareware:
	sprintf (title,
		 "                            "
		 "DOOM Shareware Startup v%i.%i"
		 "                           ",
		 VERSION/100,VERSION%100);
	break;
      case registered:
	sprintf (title,
		 "                            "
		 "DOOM Registered Startup v%i.%i"
		 "                           ",
		 VERSION/100,VERSION%100);
	break;
      case commercial:
	sprintf (title,
		 "                         "
		 "DOOM 2: Hell on Earth v%i.%i"
		 "                           ",
		 VERSION/100,VERSION%100);
	break;
/*FIXME
       case pack_plut:
	sprintf (title,
		 "                   "
		 "DOOM 2: Plutonia Experiment v%i.%i"
		 "                           ",
		 VERSION/100,VERSION%100);
	break;
      case pack_tnt:
	sprintf (title,
		 "                     "
		 "DOOM 2: TNT - Evilution v%i.%i"
		 "                           ",
		 VERSION/100,VERSION%100);
	break;
*/
      default:
	sprintf (title,
		 "                     "
		 "Public DOOM - v%i.%i"
		 "                           ",
		 VERSION/100,VERSION%100);
	break;
    }
    
    printf ("%s\n",title);

    if (devparm)
	printf("%s", D_DEVSTR);

    if (M_CheckParm("-cdrom"))
    {
	printf("%s", D_CDROM);
#ifdef _WIN32
	mkdir("c:\\doomdata");		// Windows mkdir takes no mode arg
#else
	mkdir("c:\\doomdata",0);
#endif
	strcpy (basedefault,"c:/doomdata/default.cfg");
    }	
    
    // turbo option
    if ( (p=M_CheckParm ("-turbo")) )
    {
	int     scale = 200;
	extern int forwardmove[2];
	extern int sidemove[2];
	
	if (p<myargc-1)
	    scale = atoi (myargv[p+1]);
	if (scale < 10)
	    scale = 10;
	if (scale > 400)
	    scale = 400;
	printf ("turbo scale: %i%%\n",scale);
	forwardmove[0] = forwardmove[0]*scale/100;
	forwardmove[1] = forwardmove[1]*scale/100;
	sidemove[0] = sidemove[0]*scale/100;
	sidemove[1] = sidemove[1]*scale/100;
    }
    
    // add any files specified on the command line with -file wadfile
    // to the wad list
    //
    // convenience hack to allow -wart e m to add a wad file
    // prepend a tilde to the filename so wadfile will be reloadable
    p = M_CheckParm ("-wart");
    if (p)
    {
	myargv[p][4] = 'p';     // big hack, change to -warp

	// Map name handling.
	switch (gamemode )
	{
	  case shareware:
	  case retail:
	  case registered:
	    sprintf (file,"~"DEVMAPS"E%cM%c.wad",
		     myargv[p+1][0], myargv[p+2][0]);
	    printf("Warping to Episode %s, Map %s.\n",
		   myargv[p+1],myargv[p+2]);
	    break;
	    
	  case commercial:
	  default:
	    p = atoi (myargv[p+1]);
	    if (p<10)
	      sprintf (file,"~"DEVMAPS"cdata/map0%i.wad", p);
	    else
	      sprintf (file,"~"DEVMAPS"cdata/map%i.wad", p);
	    break;
	}
	D_AddFile (file);
    }
	
    p = M_CheckParm ("-file");
    if (p)
    {
	// the parms after p are wadfile/lump names,
	// until end of parms or another - preceded parm
	modifiedgame = true;            // homebrew levels
	while (++p != myargc && myargv[p][0] != '-')
	    D_AddFile (myargv[p]);
    }

    p = M_CheckParm ("-playdemo");

    if (!p)
	p = M_CheckParm ("-timedemo");

    if (p && p < myargc-1)
    {
	sprintf (file,"%s.lmp", myargv[p+1]);
	D_AddFile (file);
	printf("Playing demo %s.lmp.\n",myargv[p+1]);
    }

    // DOOM-0203: headless CI boot-smoke. `-bootsmoke [N]` runs N game tics through
    // the normal software-render loop, then exits 0 (see D_DoomLoop). No demo lump,
    // no GPU — a "did it boot and render without crashing?" gate for GitHub Actions.
    // Distinct from -timedemo, which needs a version-matched demo lump and reports
    // via I_Error (exit 255); here a passing run is a clean exit 0.
    p = M_CheckParm ("-bootsmoke");
    if (p)
    {
	bootsmoke_tics = (p < myargc-1 && myargv[p+1][0] != '-')
		       ? atoi (myargv[p+1]) : 105;   // default 105 tics ~= 3 s @ 35 Hz
	if (bootsmoke_tics <= 0)
	    bootsmoke_tics = 105;
    }

    // get skill / episode / map from parms
    startskill = sk_medium;
    startepisode = 1;
    startmap = 1;
    autostart = false;

		
    p = M_CheckParm ("-skill");
    if (p && p < myargc-1)
    {
	startskill = myargv[p+1][0]-'1';
	autostart = true;
    }

    p = M_CheckParm ("-episode");
    if (p && p < myargc-1)
    {
	startepisode = myargv[p+1][0]-'0';
	startmap = 1;
	autostart = true;
    }
	
    p = M_CheckParm ("-timer");
    if (p && p < myargc-1 && deathmatch)
    {
	int     time;
	time = atoi(myargv[p+1]);
	printf("Levels will end after %d minute",time);
	if (time>1)
	    printf("s");
	printf(".\n");
    }

    p = M_CheckParm ("-avg");
    if (p && p < myargc-1 && deathmatch)
	printf("Austin Virtual Gaming: Levels will end after 20 minutes\n");

    p = M_CheckParm ("-warp");
    if (p && p < myargc-1)
    {
	if (gamemode == commercial)
	{
	    startmap = atoi (myargv[p+1]);
	    autostart = true;
	}
	// DOOM-0093: the E/M form also reads myargv[p+2]; without this p<myargc-2
	// guard, `-warp 3` on a non-commercial IWAD derefs argv[argc] (NULL).
	else if (p < myargc-2)
	{
	    startepisode = myargv[p+1][0]-'0';
	    startmap = myargv[p+2][0]-'0';
	    autostart = true;
	}
    }
    
    // init subsystems
    // DOOM-0147 Part C: load defaults FIRST so I_InitWidescreen can honour the
    // persisted `widescreen` pref (it sizes SCREENWIDTH, which V_Init allocates to).
    printf ("M_LoadDefaults: Load system defaults.\n");
    M_LoadDefaults ();              // load before initing other systems

    printf ("I_InitWidescreen: detect display aspect (DOOM-0147).\n");
    I_InitWidescreen ();        // sets runtime SCREENWIDTH before buffers/projection

    printf ("V_Init: allocate screens.\n");
    V_Init ();

    printf ("Z_Init: Init zone memory allocation daemon. \n");
    Z_Init ();

    printf ("W_Init: Init WADfiles.\n");
    W_InitMultipleFiles (wadfiles);

    // DOOM_Ants: the modern doom.wad is Ultimate Doom (4 episodes). Vanilla
    // only recognised retail via the doomu.wad filename; detect the extra
    // episode by lump so doom.wad gets all four episodes.
    if (gamemode == registered && W_CheckNumForName("e4m1") >= 0)
	gamemode = retail;


    // Check for -file in shareware
    if (modifiedgame)
    {
	// These are the lumps that will be checked in IWAD,
	// if any one is not present, execution will be aborted.
	char name[23][8]=
	{
	    "e2m1","e2m2","e2m3","e2m4","e2m5","e2m6","e2m7","e2m8","e2m9",
	    "e3m1","e3m3","e3m3","e3m4","e3m5","e3m6","e3m7","e3m8","e3m9",
	    "dphoof","bfgga0","heada1","cybra1","spida1d1"
	};
	int i;
	
	if ( gamemode == shareware)
	    I_Error("\nYou cannot -file with the shareware "
		    "version. Register!");

	// Check for fake IWAD with right name,
	// but w/o all the lumps of the registered version. 
	if (gamemode == registered)
	    for (i = 0;i < 23; i++)
		if (W_CheckNumForName(name[i])<0)
		    I_Error("\nThis is not the registered version.");
    }
    
    // Iff additonal PWAD files are used, print modified banner
    if (modifiedgame)
    {
	/*m*/printf (
	    "===========================================================================\n"
	    "ATTENTION:  This version of DOOM has been modified.  If you would like to\n"
	    "get a copy of the original game, call 1-800-IDGAMES or see the readme file.\n"
	    "        You will not receive technical support for modified games.\n"
	    "                      press enter to continue\n"
	    "===========================================================================\n"
	    );
	getchar ();
    }
	

    // Check and print which version is executed.
    switch ( gamemode )
    {
      case shareware:
      case indetermined:
	printf (
	    "===========================================================================\n"
	    "                                Shareware!\n"
	    "===========================================================================\n"
	);
	break;
      case registered:
      case retail:
      case commercial:
	printf (
	    "===========================================================================\n"
	    "                 Commercial product - do not distribute!\n"
	    "         Please report software piracy to the SPA: 1-800-388-PIR8\n"
	    "===========================================================================\n"
	);
	break;
	
      default:
	// Ouch.
	break;
    }

    printf ("M_Init: Init miscellaneous info.\n");
    M_Init ();

    printf ("R_Init: Init DOOM refresh daemon - ");
    R_Init ();

    printf ("\nP_Init: Init Playloop state.\n");
    P_Init ();

    printf ("I_Init: Setting up machine state.\n");
    I_Init ();

    printf ("D_CheckNetGame: Checking network game status.\n");
    D_CheckNetGame ();

    printf ("S_Init: Setting up sound.\n");
    S_Init (snd_SfxVolume /* *8 */, snd_MusicVolume /* *8*/ );

    printf ("HU_Init: Setting up heads up display.\n");
    HU_Init ();

    printf ("ST_Init: Init status bar.\n");
    ST_Init ();

    // check for a driver that wants intermission stats
    p = M_CheckParm ("-statcopy");
    if (p && p<myargc-1)
    {
	// for statistics driver
	extern  void*	statcopy;                            

	statcopy = (void*)(intptr_t)atoi(myargv[p+1]);
	printf ("External statistics registered.\n");
    }
    
    // start the apropriate game based on parms
    p = M_CheckParm ("-record");

    if (p && p < myargc-1)
    {
	G_RecordDemo (myargv[p+1]);
	autostart = true;
    }
	
    p = M_CheckParm ("-playdemo");
    if (p && p < myargc-1)
    {
	singledemo = true;              // quit after one demo
	G_DeferedPlayDemo (myargv[p+1]);
	D_DoomLoop ();  // never returns
    }
	
    p = M_CheckParm ("-timedemo");
    if (p && p < myargc-1)
    {
	G_TimeDemo (myargv[p+1]);
	D_DoomLoop ();  // never returns
    }
	
    p = M_CheckParm ("-loadgame");
    if (p && p < myargc-1)
    {
	if (M_CheckParm("-cdrom"))
	    sprintf(file, "c:\\doomdata\\"SAVEGAMENAME"%c.dsg",myargv[p+1][0]);
	else
	    sprintf(file, SAVEGAMENAME"%c.dsg",myargv[p+1][0]);
	G_LoadGame (file);
    }
	

    if ( gameaction != ga_loadgame )
    {
	if (autostart || netgame)
	    G_InitNew (startskill, startepisode, startmap);
	else
	{
	    D_StartTitle ();                // start up intro loop
	    // DOOM-0060: if both games are installed and the launcher did not
	    // already pick one (an explicit -iwad / dev flag), show the game-select
	    // chooser on top of the title screen. This rides the same path that
	    // reaches D_StartTitle, so -warp/-loadgame/net play never see it.
	    if (D_BothGamesPresent()
		&& !M_CheckParm("-iwad") && !M_CheckParm("-shdev")
		&& !M_CheckParm("-regdev") && !M_CheckParm("-comdev"))
		M_OpenGameSelect ();
	}

    }

    D_DoomLoop ();  // never returns
}
